import os
import socket
import subprocess
import sys
import time
from pathlib import Path

# Configuration
BACKEND_DIR = Path("backend")
FRONTEND_DIR = Path("frontend")
VENV_PYTHON = BACKEND_DIR / "venv" / "Scripts" / "python.exe" if sys.platform == "win32" else BACKEND_DIR / "venv" / "bin" / "python"

def find_free_port(start_port=8000, max_port=8100):
    """Find the first available port in range."""
    for port in range(start_port, max_port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("127.0.0.1", port))
                return port
            except OSError:
                continue
    raise RuntimeError("No free ports found in range")

def update_frontend_env(port):
    """Update frontend/.env with the chosen API target."""
    env_file = FRONTEND_DIR / ".env"
    target_url = f"http://127.0.0.1:{port}"
    
    print(f"✅ Configuring Frontend Proxy to: {target_url}")
    
    # Simple write (overwrite is fine for this dynamic runtime config)
    with open(env_file, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by run.py\n")
        f.write(f"VITE_API_TARGET={target_url}\n")

def main():
    print("🚀 AI CV Suite - Auto-Launcher")
    
    # 1. Find Port
    try:
        port = find_free_port()
        print(f"✅ Found available backend port: {port}")
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)

    # 2. Configure Frontend
    update_frontend_env(port)

    # 3. Start Backend
    print("🔄 Starting Backend...")
    backend_env = os.environ.copy()
    backend_env["PORT"] = str(port)
    
    # Use the venv python to run uvicorn
    backend_cmd = [str(VENV_PYTHON), "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", str(port), "--reload"]
    
    try:
        backend_proc = subprocess.Popen(backend_cmd, cwd=str(BACKEND_DIR), env=backend_env)
    except FileNotFoundError:
        print(f"❌ Could not find python at {VENV_PYTHON}. Did you create the venv?")
        sys.exit(1)

    # 4. Start Frontend
    print("🔄 Starting Frontend...")
    # We use 'npm run dev' inside frontend dir
    frontend_cmd = ["npm", "run", "dev"]
    # On Windows npm is a batch file
    shell = True if sys.platform == "win32" else False
    
    frontend_proc = subprocess.Popen(frontend_cmd, cwd=str(FRONTEND_DIR), shell=shell)

    print("✨ System Running. Press Ctrl+C to stop.")

    # 5. Monitor and Cleanup
    try:
        while True:
            time.sleep(1)
            if backend_proc.poll() is not None:
                print("❌ Backend crashed!")
                break
            if frontend_proc.poll() is not None:
                print("❌ Frontend crashed!")
                break
    except KeyboardInterrupt:
        print("\n🛑 Stopping services...")
    finally:
        backend_proc.terminate()
        frontend_proc.terminate()
        sys.exit(0)

if __name__ == "__main__":
    main()
